### ISSUE TITLE
Arrow compute kernel regards selection vector

### ISSUE THREAD

**Issue by yjshen** [apache/arrow-rs#4095] opened 2023-04-16 04:56 UTC
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

It would be great if the arrow compute kernel could regard a selection vector. Then users won't need to create slices over the existing arrays before applying computations with the compute kernel.

**Describe the solution you'd like**

A set of new compute APIs that takes a selection vector as the second argument.

For example:

```rust
pub fn sum<T: ArrowNumericType>(array: &PrimitiveArray<T>, selection_vector: &BooleanArray) -> Option<T::Native>
where
    T::Native: ArrowNativeTypeOp,
{
```

**Describe alternatives you've considered**

**Additional context**

https://github.com/apache/arrow-datafusion/pull/6003 as a use case where the selection vector would be beneficial.
https://github.com/apache/arrow-datafusion/issues/5944 for a similar proposal.

**Comment by tustvold** [comment] 2023-04-16 10:44
For primitives at least, I would expect a filter followed by the existing sum kernel to be very competitive, as it has been my experience that LLVM struggles to vectorise operations involving bitmasks.

We should definitely benchmark any new kernels against this "naive" approach

**Comment by tustvold** [comment] 2023-06-14 11:47
I'm going to close this as a duplicate of https://github.com/apache/arrow-rs/issues/3620

**Closed by tustvold** 2023-06-14 11:47 UTC
Labels: enhancement
