### ISSUE TITLE
arrow-ord: Support sortting StructArray

### ISSUE THREAD

**Issue by ParkMyCar** [apache/arrow-rs#5559] opened 2024-03-27 21:14 UTC
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Problem, I need to sort a [`StructArray`](https://docs.rs/arrow/latest/arrow/array/struct.StructArray.html) and it doesn't seem to currently be possible.

**Describe the solution you'd like**

Ideally the [`arrow_ord::sort::sort(...)`](https://docs.rs/arrow-ord/51.0.0/arrow_ord/sort/fn.sort.html) would support `StructArray`. [`pyarrow.StructArray`](https://arrow.apache.org/docs/python/generated/pyarrow.StructArray.html#pyarrow.StructArray.sort) supports this, so I believe it should be possible.

**Describe alternatives you've considered**

It doesn't seem like there are alternatives, it's just a missing API. Would love to hear though if there are ways to get a sorted `StructArray`!

**Additional context**
N/a

**Comment by tustvold** [comment] 2024-03-30 09:24
Duplicate of https://github.com/apache/arrow-rs/issues/5426

**Closed as completed** 2024-05-28 18:03 UTC
Labels: arrow, enhancement
