### ISSUE TITLE
S3 Express Append

### ISSUE THREAD

**Issue by pdeva** [apache/arrow-rs#6800] opened 2024-11-26 00:00 UTC
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Add support for [S3 Express Append](https://aws.amazon.com/about-aws/whats-new/2024/11/amazon-s3-express-one-zone-append-data-object)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment] 2024-11-26 06:36
Closing as a duplicate of https://github.com/apache/arrow-rs/issues/4966

**Closed** 2024-11-26 06:37 UTC
Labels: question
