### ISSUE TITLE
Empty and Null structarray fails to IPC roundtrip 

### ISSUE THREAD

**Issue by debugmiller** [apache/arrow-rs#5920] opened 2024-06-19 19:57 UTC
**Describe the bug**
A StructArray that has no fields and where all rows are null does not round trip correctly. But instead fails during deserialize with:
```
InvalidArgumentError("all columns in a record batch must have the specified row count")
```

**To Reproduce**
```rust
use std::error::Error;
use std::io::Cursor;
use std::sync::Arc;

use arrow::{array::{Array, RecordBatch, StructArray}, ipc::{reader::StreamReader, writer::{IpcWriteOptions, StreamWriter}, MetadataVersion}};
use arrow_schema::{Field, Fields, Schema};

fn serialize_stream(record: &RecordBatch) -> Vec<u8> {
    // Use 8-byte alignment so that the various `truncate_*` tests can be compactly written,
    // without needing to construct a giant array to spill over the 64-byte default alignment
    // boundary.
    const IPC_ALIGNMENT: usize = 8;

    let mut stream_writer = StreamWriter::try_new_with_options(
        vec![],
        record.schema_ref(),
        IpcWriteOptions::try_new(IPC_ALIGNMENT, false, MetadataVersion::V5).unwrap(),
    )
    .unwrap();
    stream_writer.write(record).unwrap();
    stream_writer.finish().unwrap();
    stream_writer.into_inner().unwrap()
}

fn deserialize_stream(bytes: Vec<u8>) -> RecordBatch {
    let mut stream_reader = StreamReader::try_new(Cursor::new(bytes), None).unwrap();
    stream_reader.next().unwrap().unwrap()
}

fn empty_null_struct_array_roundtrip() {
    fn create_batch() -> RecordBatch {
        let struct_array = StructArray::new_null(Fields::empty(), 3);

        let schema = Schema::new(vec![Field::new(
            "struct_array",
            struct_array.data_type().clone(),
            true,
        )]);

        RecordBatch::try_new(Arc::new(schema), vec![Arc::new(struct_array)]).unwrap()
    }

    let record_batch = create_batch();
    let deserialized_batch = deserialize_stream(serialize_stream(&record_batch));

    assert!(
        serialize_stream(&record_batch).len() == serialize_stream(&record_batch).len()
    );

    let structs = deserialized_batch
        .column(0)
        .as_any()
        .downcast_ref::<StructArray>()
        .unwrap();

    assert!(structs.is_null(0));
    assert!(structs.is_null(1));
    assert!(structs.is_null(2));
    assert_eq!(record_batch, deserialized_batch);
}

fn main() -> Result<(), Box<dyn Error>> {
    empty_null_struct_array_roundtrip();
    Ok(())
}
```

**Expected behavior**
Should roundtrip 

**Additional context**

**Comment by kawadakk** [comment] 2024-06-21 10:16
This looks like a duplicate of #4643.

**Closed** 2024-06-21 10:20 UTC
Labels: bug
