### ISSUE TITLE
Glommio based IO version for Parquet

### ISSUE THREAD

**Issue by ozgrakkurt** [apache/arrow-rs#5240] opened 2023-12-24 07:17 UTC
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I want to read parquet files with less latency/better throughput. [Glommio](https://github.com/DataDog/glommio) is a thread per core library that utilizes io_uring and direct_io. Direct IO is particularly nice for my case and I image for many other parquet use cases, because my usecase doesn't benefit at all from caching the parquet files in Linux PageCache, it even suffers from it. Also I use fast nvme disks to store the parquet files so direct_io/io_uring can give a big performance boost.

https://itnext.io/modern-storage-is-plenty-fast-it-is-the-apis-that-are-bad-6a68319fbc1a
https://www.phoronix.com/news/OpenZFS-DirectIO-Performance

**Describe the solution you'd like**
Have a alternative io implementation for parquet similar to the async feature (it uses tokio). 

It will implement glommio_reader, glommio_writer etc. similar to async_reader, async_writer etc.

**Describe alternatives you've considered**
Can open the file with O_DIRECT flag and just read with current async impl or sync impl but then it will crash because of unaligned buffers etc.

Just using glommio should be better since don't need to implement alignment of buffers etc. Also glommio already has io_uring thread per core architecture etc. which is very nice for building database like systems.

**Comment by tustvold** [comment] 2023-12-24 09:00
The async reader and writer are designed to not be tightly coupled to tokio, can they be used for this?

**Comment by ozgrakkurt** [comment] 2023-12-24 09:16
> The async reader and writer are designed to not be tightly coupled to tokio, can they be used for this?

So can just add a `glommio` feature to `object_store` crate and add a struct that implements `ObjectStore` trait and use it with the `async_reader`?

**Comment by tustvold** [comment] 2023-12-24 09:27
I think ObjectStore would run into issues with send bounds, I was thinking you could implement AsyncFileReader in your application using glommio. We may need to tweak the trait to make the futures associated types, so they can use LocalBoxFuture in this case, but I think it should be tractable

**Comment by tustvold** [comment] 2023-12-24 12:07
FWIW I would be interested in any benchmarks of this, typically on modern hardware parquet decoding ends up CPU bound not IO bound when reading from local disk.

**Comment by tustvold** [comment] 2023-12-24 22:34
> Theoretically it should be able to decode faster than disk read

Certainly decoding plain encoded primitives can approach the memory bandwidth of the machine. However, the same is not typically true of BYTE_ARRAY, where the data dependency introduced by the lengths, among other overheads, tends to get in the way.

I'll be very interested to see any results you can share, NVMe opens a lot of cool possibilities 👍

**Comment by ozgrakkurt** [comment] 2024-01-02 08:55
@tustvold so far I got initial version of this to work. The IO itself is 2x-3x as fast as tokio/stdlib io but the decoding is the main bottleneck like you said. I suspect I can tune decoding speed a lot, we currently plain encode columns with many many repetitions and then lz4 compress them so this is not very ideal I am guessing.

**Comment by tustvold** [comment] 2024-03-16 22:25
I'm going to close this as a duplicate of #4631

**Closed by tustvold** 2024-03-16 22:25 UTC
Labels: enhancement
