### ISSUE TITLE
Support `List` in `compare_op`

### ISSUE THREAD

**Issue by Weijun-H** [apache/arrow-rs#5572] opened 2024-03-30 08:39 UTC
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

```rust
//  [[0, 1, 2], [3, 4, 5], [6, 7]]
let values = Int32Array::from(vec![0, 1, 2, 3, 4, 5, 6, 7]);
let offsets = OffsetBuffer::new(ScalarBuffer::from(vec![0, 3, 6, 8]));
let field = Arc::new(Field::new("item", DataType::Int32, true));
let a = ListArray::new(field, offsets, Arc::new(values), None);
let b = a.clone();

let r = eq(&a, &b).unwrap();
assert!(r.value(0));
```

```bash
thread 'cmp::tests::test_list' panicked at arrow-ord/src/cmp.rs:695:28:
called `Result::unwrap()` on an `Err` value: InvalidArgumentError("Invalid comparison operation: List(Field { name: \"item\", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }) == List(Field { name: \"item\", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} })")
```

**Describe the solution you'd like**

support `List` in `compare_op`

https://github.com/apache/arrow-rs/blob/55723980d394465953705ea9af9d7069bd588f73/arrow-ord/src/cmp.rs#L169-L286

**Describe alternatives you've considered**

**Additional context**

https://github.com/apache/arrow-datafusion/issues/9857

**Comment by tustvold** [comment] 2024-03-30 09:24
Duplicate of https://github.com/apache/arrow-rs/issues/5426

**Closed** 2024-05-28 11:25 UTC
Labels: enhancement
