### ISSUE TITLE
SerializedFileReader panicked on next of RowIter

### ISSUE THREAD

**Issue by WaterKnight1998** [apache/arrow-rs#3745] opened 2023-02-22 09:43 UTC
**Describe the bug**

I am iterating the RowIter of a `SerializedFileReader`, when I call iter.next() I get the following error:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value',
```

**To Reproduce**
```rust
    let mut file = File::open("test.parquet").unwrap();
    let reader = SerializedFileReader::new(file).unwrap();
    println!("Number of rows: {}", reader.metadata().num_row_groups());

    let mut iter = reader.get_row_iter(None).unwrap();
    let element = iter.next();
```

**Expected behavior**
It should return the row

**Additional context**
Parquet package version 33.0

**Comment by Dandandan** [comment] 2023-02-22 12:16
Looking at your panic, it doesn't error on `.next()` but on `unwrap`

**Comment by tustvold** [comment] 2023-02-22 12:29
I suspect this is a duplicate of https://github.com/apache/arrow-rs/issues/2394 but without a reproducer I cannot debug this

**Closed** 2023-06-01 14:55 UTC
Labels: bug
