### ISSUE TITLE
Allow non-utf8 characters in arrow_csv::reader::infer_reader_schema

### ISSUE THREAD

**Issue by alexkreidler** [apache/arrow-rs#3324] opened 2022-12-10 06:57 UTC
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I'm writing some code to infer types from a bunch of different CSV files. I ran it on one and got this error:
```
Sampled 100000 lines from ./backup/Book-0.tsv
Error: Csv error: Encountered UTF-8 error while reading CSV file: invalid utf-8: invalid UTF-8 in field 4 near byte index 149
```
because it contained this string `serving as the navy�s liaison`

**Describe the solution you'd like**
I'd like to be able to pass an additional field to the `ReaderOptions` struct parameter to `infer_reader_schema_with_csv_options`, or better yet `infer_reader_schema` function, and have the library silently continue on non-utf8 values. It could still output their schema type as utf8, or a `NullType`, or even better `BinaryType`.

**Describe alternatives you've considered**
I could handle this in my code. I imagine there may be many users with non-utf8 CSVs that would still like to pass the data verbatim through Apache Arrow.

**Additional context**

Diving into the code, it looks like we'd need to use `read_byte_record` instead of `read_record` below. I'm not sure the extent of changes this would require in the `arrow-csv` crate.

https://github.com/apache/arrow-rs/blob/9e39f96b121d88b7427295bd326d14bb78d0fb39/arrow-csv/src/reader.rs#L487-L499

**Comment by tustvold** [comment] 2022-12-10 12:55
> It could still output their schema type as utf8

It would need to infer it as binary, as UTF-8 data is not allowed to contain UTF-8 data.

As it stands the crate does not support reading or writing binary data, I would be happy to review PRs that would add support for this, but there are some open questions on what this might look like.

**Comment by tustvold** [comment] 2023-06-01 14:57
Closing as a duplicate of #3291

**Closed by tustvold** 2023-06-01 14:57 UTC
Labels: enhancement
