### ISSUE TITLE
concat::tests::test_string_dictionary_merge failure 

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#5292] opened 2024-01-09 12:23 UTC
**Describe the bug**
While veriying the arrow 50 release on a mac M3 the verifiy script failed for me. 

However, it seems to also happen on a local checkout after dependencies are updated, so I don't think it is anything related to the new code. 

Also, looking at the code https://github.com/apache/arrow-rs/blob/db811083669df66992008c9409b743a2e365adb0/arrow-select/src/concat.rs#L549

It seems like the new answer might actually be better than the old.

**To Reproduce**
```shell
wget  https://dist.apache.org/repos/dist/dev/arrow/apache-arrow-rs-50.0.0-rc1/apache-arrow-rs-50.0.0.tar.gz
tar xf apache-arrow-rs-50.0.0.tar.gz
cd apache-arrow-rs-50.0.0
./dev/release/verify-release-candidate.sh 50.0.0 1
```

This results in a failure:
```
---- concat::tests::test_string_dictionary_merge stdout ----
thread 'concat::tests::test_string_dictionary_merge' panicked at arrow-select/src/concat.rs:572:9:
assertion `left == right` failed
  left: 30
 right: 33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    concat::tests::test_string_dictionary_merge

test result: FAILED. 149 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.09s

error: test failed, to rerun pass `-p arrow-select --lib`
```

**Expected behavior**
Strangely when I run this on a checkout, it passes fine:

```
(venv) andrewlamb@Andrews-MacBook-Pro:~/Software/arrow-rs$ cargo test -p arrow-select --all-features -- test_string_dictionary_merge
    Finished test [unoptimized + debuginfo] target(s) in 0.04s
     Running unittests src/lib.rs (target/debug/deps/arrow_select-26516f67a5fab62a)

running 1 test
test concat::tests::test_string_dictionary_merge ... ok
```

However, when I did `cargo update` locally to update dependencies in my checkout then the test started failing for me

```shell
cargo update
    Updating crates.io index
    Updating ahash v0.8.6 -> v0.8.7
    Updating anyhow v1.0.77 -> v1.0.79
    Updating async-trait v0.1.75 -> v0.1.76
    Updating base64 v0.21.5 -> v0.21.6
    Updating bstr v1.8.0 -> v1.9.0
    Updating chrono-tz v0.8.4 -> v0.8.5
    Updating clap v4.4.11 -> v4.4.14
    Updating clap_builder v4.4.11 -> v4.4.14
    Updating getrandom v0.2.11 -> v0.2.12
    Updating iana-time-zone v0.1.58 -> v0.1.59
    Updating is-terminal v0.4.9 -> v0.4.10
    Updating libc v0.2.151 -> v0.2.152
    Updating memchr v2.6.4 -> v2.7.1
    Updating pyo3 v0.20.0 -> v0.20.2
    Updating pyo3-build-config v0.20.0 -> v0.20.2
    Updating pyo3-ffi v0.20.0 -> v0.20.2
    Updating semver v1.0.20 -> v1.0.21
    Updating serde_json v1.0.108 -> v1.0.109
    Updating syn v2.0.32 -> v2.0.43
    Updating target-lexicon v0.12.12 -> v0.12.13
    Updating tempfile v3.8.1 -> v3.9.0
    Updating windows-core v0.51.1 -> v0.52.0
(venv) andrewlamb@Andrews-MacBook-Pro:~/Software/arrow-rs$ cargo test -p arrow-select --all-features -- test_string_dictionary_merge
  Downloaded getrandom v0.2.12
  Downloaded 1 crate (36.2 KB) in 0.31s
   Compiling libc v0.2.152
   Compiling once_cell v1.19.0
   Compiling ahash v0.8.7
   Compiling iana-time-zone v0.1.59
   Compiling chrono v0.4.31
   Compiling getrandom v0.2.12
   Compiling rand_core v0.6.4
   Compiling rand_chacha v0.3.1
   Compiling arrow-array v49.0.0 (/Users/andrewlamb/Software/arrow-rs/arrow-array)
   Compiling rand v0.8.5
   Compiling arrow-select v49.0.0 (/Users/andrewlamb/Software/arrow-rs/arrow-select)
    Finished test [unoptimized + debuginfo] target(s) in 4.08s
     Running unittests src/lib.rs (target/debug/deps/arrow_select-5fb2879644374192)

running 1 test
test concat::tests::test_string_dictionary_merge ... FAILED

failures:

---- concat::tests::test_string_dictionary_merge stdout ----
thread 'concat::tests::test_string_dictionary_merge' panicked at arrow-select/src/concat.rs:572:9:
assertion `left == right` failed
  left: 30
 right: 33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    concat::tests::test_string_dictionary_merge

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 149 filtered out; finished in 0.00s
```

**Additional context**

**Comment by tustvold** [comment] 2024-01-09 12:35
I think this is a duplicate of https://github.com/apache/arrow-rs/issues/5255

**Comment by tustvold** [comment] 2024-01-19 10:56
Closing as a duplicate

**Closed by tustvold** 2024-01-19 10:56 UTC
Labels: bug
