### ISSUE TITLE
The CI pipeline `Archery test With other arrow` is broken

### ISSUE THREAD

**Issue by viirya** [apache/arrow-rs#5742] opened 2024-05-10 14:36 UTC
**Describe the bug**

Our CI pipeline (Archery test With other arrows) seems broken:

https://github.com/apache/arrow-rs/actions/runs/9033207356/job/24824792381?pr=5741

```
  = note: /opt/conda/envs/arrow/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-d2ef02247056996e.rlib(std-d2ef02247056996e.std.e4dfbc2c3f4b09f1-cgu.0.rcgu.o): in function `std::sys::pal::unix::stack_overflow::imp::sigstack_size':
          /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys/pal/unix/stack_overflow.rs:216: undefined reference to `getauxval'
          /opt/conda/envs/arrow/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys/pal/unix/stack_overflow.rs:216: undefined reference to `getauxval'
          collect2: error: ld returned 1 exit status
```

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by tustvold** [comment] 2024-05-10 14:38
Duplicate of https://github.com/apache/arrow-rs/issues/5719

**Closed by tustvold** 2024-05-10 14:38 UTC
Labels: bug

**Comment by viirya** [comment] 2024-05-10 14:40
Ah, not notice that. Thanks @tustvold

**Comment by tustvold** [comment] 2024-05-10 17:07
`label_issue.py` automatically added labels {'arrow'} from #5741
