### ISSUE TITLE
Change default branch name from master to main

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-rs#3569] opened 2023-01-19 19:40 UTC
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
For context: https://github.com/github/renaming

**Describe the solution you'd like**
Change default branch name from master to main

**Describe alternatives you've considered**

**Additional context**

**Comment by assignUser** [comment] 2023-01-19 22:07
Duplicate of #2173  ;)

**Comment by Jefffrey** [comment] 2024-04-27 01:56
Closed as duplicate

**Closed by Jefffrey** 2024-04-27 01:56 UTC
Labels: enhancement
