### ISSUE TITLE
Parquet schema hint doesn't support integer types upcasting

### ISSUE THREAD

**Issue by gruuya** [apache/arrow-rs#6891] opened 2024-12-17 13:42 UTC
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
The present matching logic for overriding a Parquet schema doesn't support Integer up-casting https://github.com/apache/arrow-rs/blob/123045cc766d42d1eb06ee8bb3f09e39ea995ddc/parquet/src/arrow/schema/primitive.rs#L40-L49

**Describe the solution you'd like**
I'd like to be able to override any integer type as long is avoids precision loss (though it could be argued that even this is too conservative).

**Describe alternatives you've considered**
Apply some kind of a schema adapter/mask at a higher level, e.g. via some DataFusion extension mechanism.

**Additional context**
Related to https://github.com/apache/iceberg-rust/issues/813.

**Comment by tustvold** [comment] 2024-12-17 22:18
Closing as duplicate of #6735

**Closed by tustvold** 2024-12-17 22:18 UTC
Labels: enhancement
